services:
    nacholibre.rich_uploader_type.form:
        class: nacholibre\RichUploaderBundle\Form\Type\RichUploaderType
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: form.type }

    nacholibre.rich_image.service:
        class: nacholibre\RichUploaderBundle\Services\RichImageService
        arguments: ["@doctrine.orm.entity_manager"]

    app.helper_extension:
        class: nacholibre\RichUploaderBundle\Twig\HelperExtension
        public: false
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
