services:
    nacholibre.rich_image.form:
        class: nacholibre\RichImageBundle\Form\Type\RichImageType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
